services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: fyyur-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fyyurdb
    volumes:
      - fyyur-pgdata:/var/lib/postgresql/data

volumes:
  fyyur-pgdata:
